const String APP_TITLE = 'Test App';

const int STATE_DEFAULT = 0;

const int STATE_LAYOUT_GRID = 101;
const int STATE_LAYOUT_FULL_STRETCHED = 102;
const int STATE_LAYOUT_SCROLLABLE_FORM = 103;
const int STATE_LAYOUT_SILVERS = 104;
const int STATE_LAYOUT_SILVERS_PAGES = 105;

const int STATE_MESSAGE = 210;
const int STATE_GOOGLE_SIGN_IN = 220;
const int STATE_GOOGLE_API_PEOPLE = 221;
const int STATE_GOOGLE_API_DRIVER = 222;
const int STATE_GOOGLE_API_MAP = 223;

const int STATE_PAYPAL_API_BRAINTREE = 230;

const int STATE_MODULE_PERSON = 200;
const int STATE_MODULE_ALBUM = 300;
const int STATE_MODULE_CONFIGURATION = 800;
const int STATE_MODULE_CONTACT = 600;
const int STATE_MODULE_CONTACT_ONE = 601;
const int STATE_MODULE_CONTACT_NUMBER = 602;
const int STATE_MODULE_CONTACT_SPINNER = 690;
const String MODULE_CONTACT_CACHE = '<MODULE_CONTACT_CACHE>';
const String MODULE_CONTACT_STORAGE_MONGO_ATLAS = '<MODULE_CONTACT_STORAGE_MONGO_ATLAS>';
const String MODULE_CONTACT_STORAGE_GOOGLE_DRIVE = '<MODULE_CONTACT_STORAGE_GOOGLE_DRIVE>';

const int STATE_SHARE_CONTENT = 700;
const int STATE_CAMERA_IMAGE_PICKER = 720;

const int STATE_ERROR_UNEXPECTED = 991;
